### ISSUE TITLE
no recovery from ingester (readstreams) tracebacks 

### ISSUE THREAD

**Issue by phycodurus** [TOMToolkit/tom_nonlocalizedevents#8]
Here's an example (below). We should recover from errors like these. 
In this example, we are successful in downloading the baystar.multiorder.fits file from GraceDB, but
the EventLocalization does not exist.

The end result is this:
```
%4|1677178238.646|MAXPOLL|rdkafka#consumer-2| [thrd:main]: Application maximum poll interval (300000ms) exceeded by 237ms (adjust max.poll.interval.ms for long-running message processing): leaving group
%3|1677181244.504|FAIL|rdkafka#consumer-2| [thrd:GroupCoordinator]: GroupCoordinator: kafka2.gcn.nasa.gov:9092: SASL authentication error: {"status":"invalid_token"} (after 410ms in state AUTH_REQ)
%3|1677181283.967|FAIL|rdkafka#consumer-2| [thrd:GroupCoordinator]: GroupCoordinator: kafka2.gcn.nasa.gov:9092: SASL authentication error: {"status":"invalid_token"} (after 406ms in state AUTH_REQ, 6 identical error(s) suppressed)

```

```
Ingested a new GW event with id MS230223s from alertstream
Creating localization for MS230223s with MOC skymap https://gracedb.ligo.org/api/superevents/MS230223s/files/bayestar.multiorder.fits
Downloading https://gracedb.ligo.org/api/superevents/MS230223s/files/bayestar.multiorder.fits [Done]
/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1416: RuntimeWarning:

DateTimeField EventLocalization.date received a naive datetime (2023-02-23 18:45:31) while time zone support is active.

Downloading https://gracedb.ligo.org/api/superevents/MS230223s/files/bayestar.multiorder.fits [Done]
Exception in thread GCNClassicAlertStream:
Traceback (most recent call last):
  File "/opt/lcogt-python39/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/astropy/utils/data.py", line 398, in get_readable_fileobj
    yield fileobj
  File "/home/llindstrom/dev/tom_nonlocalizedevents/tom_nonlocalizedevents/healpix_utils.py", line 66, in create_localization_for_multiorder_fits
    localization = EventLocalization.objects.get(nonlocalizedevent=nonlocalizedevent, date=creation_date)
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
tom_nonlocalizedevents.models.EventLocalization.DoesNotExist: EventLocalization matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/lcogt-python39/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/lcogt-python39/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/tom_alertstreams/alertstreams/gcn.py", line 51, in listen
    self.alert_handler[topic](alert)
  File "/home/llindstrom/dev/tom_nonlocalizedevents/tom_nonlocalizedevents/alertstream_handlers/gw_event_handler.py", line 62, in handle_message
    localization = create_localization_for_multiorder_fits(
  File "/home/llindstrom/dev/tom_nonlocalizedevents/tom_nonlocalizedevents/healpix_utils.py", line 73, in create_localization_for_multiorder_fits
    localization = EventLocalization.objects.create(
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/django/db/models/base.py", line 787, in save_base
    post_save.send(
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/llindstrom/dev/tom_nonlocalizedevents/tom_nonlocalizedevents/signals/handlers.py", line 27, in cb_post_save_event_localization
    update_all_credible_region_percents_for_candidates(instance)
  File "/home/llindstrom/dev/tom_nonlocalizedevents/tom_nonlocalizedevents/healpix_utils.py", line 133, in update_all_credible_region_percents_for_candidates
    update_credible_region_percent_for_candidates(eventlocalization, probability, event_candidate_ids)
  File "/home/llindstrom/dev/tom_nonlocalizedevents/tom_nonlocalizedevents/healpix_utils.py", line 175, in update_credible_region_percent_for_candidates
    results = session.execute(query)
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
%4|1677178238.646|MAXPOLL|rdkafka#consumer-2| [thrd:main]: Application maximum poll interval (300000ms) exceeded by 237ms (adjust max.poll.interval.ms for long-running message processing): leaving group
```

**Comment by phycodurus** [comment]
In the following example, we timeout while trying to retreive the baystar.multiorder.fits file from GraceDB:

```
Creating localization for MS230226k with MOC skymap https://gracedb.ligo.org/api/superevents/MS230226k/files/bayestar.multiorder.fits
Exception in thread GCNClassicAlertStream:
Traceback (most recent call last):
  File "/opt/lcogt-python39/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/lcogt-python39/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/tom_alertstreams/alertstreams/gcn.py", line 51, in listen
    self.alert_handler[topic](alert)
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/tom_nonlocalizedevents/alertstream_handlers/gw_event_handler.py", line 62, in handle_message
    localization = create_localization_for_multiorder_fits(
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/tom_nonlocalizedevents/healpix_utils.py", line 63, in create_localization_for_multiorder_fits
    header = fits.getheader(multiorder_fits_url, 1)
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/astropy/io/fits/convenience.py", line 103, in getheader
    ----------
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/astropy/io/fits/convenience.py", line 1071, in _getext
    # (extname, extver) tuple
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 175, in fitsopen
    
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 410, in fromfile
    
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 1062, in _readfrom
    
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/astropy/io/fits/file.py", line 151, in __init__
    
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/astropy/utils/data.py", line 1366, in download_file
    http_headers=None,
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/astropy/utils/data.py", line 1167, in _download_file_from_source
    if "cafile" not in ssl_context and certifi is not None:
  File "/home/llindstrom/dev/tom-demo/env/lib/python3.9/site-packages/astropy/utils/data.py", line 1104, in _try_url_open
    ----------
  File "/opt/lcogt-python39/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/opt/lcogt-python39/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/lcogt-python39/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/lcogt-python39/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/lcogt-python39/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/opt/lcogt-python39/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/opt/lcogt-python39/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/opt/lcogt-python39/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/lcogt-python39/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/opt/lcogt-python39/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/lcogt-python39/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
%4|1677521407.842|MAXPOLL|rdkafka#consumer-3| [thrd:main]: Application maximum poll interval (300000ms) exceeded by 161ms (adjust max.poll.interval.ms for long-running message processing): leaving group

```
